// <auto-generated />
using System;
using BackEnd.Data.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Data.DB.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260728195929_AddSiteSettings")]
    partial class AddSiteSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackEnd.Data.Entities.ContactUs.ContactUs", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactUs");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.FAQ.FAQ", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sequense")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FAQs");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.Package.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Badge")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("Features")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.Portfolio.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PortfolioFiles", "portfolio");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MyProperty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.Role.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconColorCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.Role.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Permissions")
                        .HasColumnType("int");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermission");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.SiteSettings.AboutMeSection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AboutStatsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AboutStatsId");

                    b.ToTable("AboutMeSection");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.SiteSettings.AboutStats", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActiveCustomers")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerSatisfaction")
                        .HasColumnType("int");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<int>("SuccessProjects")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AboutStats");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.SiteSettings.GeneralSiteInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GeneralSiteInformation");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.SiteSettings.MenuSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ImplementationStyle")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<Guid?>("SiteSettingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SiteSettingId");

                    b.ToTable("MenuSetting");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.SiteSettings.ProjectSectionSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ProjectSectionSetting");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.SiteSettings.ProjectSectionSettingOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("ProjectIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProjectSectionSettingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectSectionSettingId");

                    b.ToTable("ProjectSectionSettingOption");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.SiteSettings.SiteLinks", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Sequense")
                        .HasColumnType("int");

                    b.Property<Guid?>("SiteSettingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SiteSettingId");

                    b.ToTable("SiteLinks");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.SiteSettings.SiteSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AboutMeSectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GeneralSiteInformationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProjectSectionSettingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("SiteIsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SpecializedServicesSectionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AboutMeSectionId");

                    b.HasIndex("GeneralSiteInformationId");

                    b.HasIndex("ProjectSectionSettingId");

                    b.HasIndex("SpecializedServicesSectionId");

                    b.ToTable("SiteSettings");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.SiteSettings.SpecializedServicesSection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SpecializedServicesSection");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.SiteSettings.SpecializedServicesSectionOptions", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SpecializedServicesSectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SpecializedServicesSectionId");

                    b.ToTable("SpecializedServicesSectionOptions");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.Skills.TechnicalSkills", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SkillPercentage")
                        .HasColumnType("int");

                    b.Property<int>("SkillTypes")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TechnicalSkills");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberIsVerify")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.User.UserBlackList", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserBlackList");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.User.UserOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserOtp");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.User.UserOtpSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserOtpSession");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.User.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.User.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashRefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSession");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.User.UserSessionBlackList", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSessionBlackList");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.Portfolio.Portfolio", b =>
                {
                    b.OwnsOne("BackEnd.Data.Entities.Portfolio.PortfolioFile", "File", b1 =>
                        {
                            b1.Property<Guid>("PortfolioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreationDate")
                                .HasColumnType("datetime2");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ImageAddress")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("IsImage")
                                .HasColumnType("bit");

                            b1.Property<bool>("IsVideo")
                                .HasColumnType("bit");

                            b1.Property<string>("VideoAddress")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PortfolioId");

                            b1.ToTable("PortfolioFiles", "portfolio");

                            b1.WithOwner()
                                .HasForeignKey("PortfolioId");
                        });

                    b.Navigation("File")
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Data.Entities.Role.RolePermission", b =>
                {
                    b.HasOne("BackEnd.Data.Entities.Role.Role", null)
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Data.Entities.SiteSettings.AboutMeSection", b =>
                {
                    b.HasOne("BackEnd.Data.Entities.SiteSettings.AboutStats", "AboutStats")
                        .WithMany()
                        .HasForeignKey("AboutStatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AboutStats");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.SiteSettings.MenuSetting", b =>
                {
                    b.HasOne("BackEnd.Data.Entities.SiteSettings.SiteSetting", null)
                        .WithMany("MenuSettings")
                        .HasForeignKey("SiteSettingId");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.SiteSettings.ProjectSectionSettingOption", b =>
                {
                    b.HasOne("BackEnd.Data.Entities.SiteSettings.ProjectSectionSetting", null)
                        .WithMany("Options")
                        .HasForeignKey("ProjectSectionSettingId");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.SiteSettings.SiteLinks", b =>
                {
                    b.HasOne("BackEnd.Data.Entities.SiteSettings.SiteSetting", null)
                        .WithMany("SiteLinks")
                        .HasForeignKey("SiteSettingId");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.SiteSettings.SiteSetting", b =>
                {
                    b.HasOne("BackEnd.Data.Entities.SiteSettings.AboutMeSection", "AboutMeSection")
                        .WithMany()
                        .HasForeignKey("AboutMeSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Data.Entities.SiteSettings.GeneralSiteInformation", "GeneralSiteInformation")
                        .WithMany()
                        .HasForeignKey("GeneralSiteInformationId");

                    b.HasOne("BackEnd.Data.Entities.SiteSettings.ProjectSectionSetting", "ProjectSectionSetting")
                        .WithMany()
                        .HasForeignKey("ProjectSectionSettingId");

                    b.HasOne("BackEnd.Data.Entities.SiteSettings.SpecializedServicesSection", "SpecializedServicesSection")
                        .WithMany()
                        .HasForeignKey("SpecializedServicesSectionId");

                    b.Navigation("AboutMeSection");

                    b.Navigation("GeneralSiteInformation");

                    b.Navigation("ProjectSectionSetting");

                    b.Navigation("SpecializedServicesSection");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.SiteSettings.SpecializedServicesSectionOptions", b =>
                {
                    b.HasOne("BackEnd.Data.Entities.SiteSettings.SpecializedServicesSection", null)
                        .WithMany("Options")
                        .HasForeignKey("SpecializedServicesSectionId");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.User.UserBlackList", b =>
                {
                    b.HasOne("BackEnd.Data.Entities.User.User", null)
                        .WithMany("UserBlackList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Data.Entities.User.UserOtp", b =>
                {
                    b.HasOne("BackEnd.Data.Entities.User.User", null)
                        .WithMany("UserOtps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Data.Entities.User.UserOtpSession", b =>
                {
                    b.HasOne("BackEnd.Data.Entities.User.User", null)
                        .WithMany("UserOtpSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Data.Entities.User.UserRole", b =>
                {
                    b.HasOne("BackEnd.Data.Entities.User.User", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Data.Entities.User.UserSession", b =>
                {
                    b.HasOne("BackEnd.Data.Entities.User.User", null)
                        .WithMany("UserSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Data.Entities.User.UserSessionBlackList", b =>
                {
                    b.HasOne("BackEnd.Data.Entities.User.User", null)
                        .WithMany("UserSessionBlackList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Data.Entities.Role.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.SiteSettings.ProjectSectionSetting", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.SiteSettings.SiteSetting", b =>
                {
                    b.Navigation("MenuSettings");

                    b.Navigation("SiteLinks");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.SiteSettings.SpecializedServicesSection", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("BackEnd.Data.Entities.User.User", b =>
                {
                    b.Navigation("UserBlackList");

                    b.Navigation("UserOtpSessions");

                    b.Navigation("UserOtps");

                    b.Navigation("UserRoles");

                    b.Navigation("UserSessionBlackList");

                    b.Navigation("UserSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
